project:
  type: website
  output-dir: _site

website:
  title: "Kurstitel"
  navbar:
    left:
      - text: home
        file: index.qmd
      - text: lecture plan
        file: lecture-plan.qmd
      - text: exercises
        file: exercises/index.qmd

format:
  html:
    toc: true

execute:
  freeze: auto
